# Generated by Django 4.1.2 on 2022-11-02 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contractor_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contractor_name", models.CharField(blank=True, max_length=250)),
                ("con_address", models.CharField(blank=True, max_length=250)),
                ("licensed_no", models.IntegerField(blank=True, null=True)),
                ("tel_no", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "coren_or_nemsa_competency",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("reg_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="technicalEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_survey_mapping",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "load_demand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "equipment_sizing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="contract_application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "connectiontype",
                    models.CharField(
                        choices=[
                            ("transformer installation", "transformer installation"),
                            ("transformer uprating", "transformer uprating"),
                            ("relocation", "relocation"),
                            (
                                "change of transformer source",
                                "change of transformer source",
                            ),
                            ("others", "others"),
                        ],
                        default="transformer installation",
                        max_length=100,
                    ),
                ),
                ("capacity", models.CharField(blank=True, max_length=250)),
                ("voltage_ratio", models.CharField(blank=True, max_length=250)),
                ("route_length_km", models.CharField(blank=True, max_length=250)),
                ("add_house_no", models.CharField(blank=True, max_length=250)),
                ("add_street", models.CharField(blank=True, max_length=250)),
                ("add_town_or_city", models.CharField(blank=True, max_length=250)),
                ("add_lga", models.CharField(blank=True, max_length=250)),
                ("add_state", models.CharField(blank=True, max_length=250)),
                ("est_load_of_premises", models.CharField(blank=True, max_length=250)),
                (
                    "useofpremises",
                    models.CharField(
                        choices=[
                            ("residential", "residential"),
                            ("commercial", "commercial"),
                            ("industrial", "industrial"),
                        ],
                        default="residential",
                        max_length=100,
                    ),
                ),
                (
                    "letter_of_donation_dss",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "nemsa_test_cert",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "transformer_waranty",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "transformer_test_cert",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "date_of_application",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("isMd", models.BooleanField(default=False)),
                ("Mdcomment", models.TextField(blank=True, null=True)),
                ("Md_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Md_approve", models.BooleanField(default=False)),
                ("Md_dissaprove", models.BooleanField(default=False)),
                ("isTm", models.BooleanField(default=False)),
                ("Tmcomment", models.TextField(blank=True, null=True)),
                ("Tm_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Tm_approve", models.BooleanField(default=False)),
                ("Tm_dissaprove", models.BooleanField(default=False)),
                ("isTe", models.BooleanField(default=False)),
                ("Tecomment", models.TextField(blank=True, null=True)),
                ("Tedate", models.DateTimeField(auto_now_add=True, null=True)),
                ("Te_approve", models.BooleanField(default=False)),
                ("Te_dissaprove", models.BooleanField(default=False)),
                ("isHnp_D", models.BooleanField(default=False)),
                ("Hnp_D_comment", models.TextField(blank=True, null=True)),
                ("Hnp_D_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Hnp_D_approve", models.BooleanField(default=False)),
                ("Hnp_D_dissaprove", models.BooleanField(default=False)),
                ("isCto", models.BooleanField(default=False)),
                ("Ctocomment", models.TextField(blank=True, null=True)),
                ("Ctodate", models.DateTimeField(auto_now_add=True, null=True)),
                ("Ctoapprove", models.BooleanField(default=False)),
                ("Ctodissaprove", models.BooleanField(default=False)),
                ("isHse_pc_np_d", models.BooleanField(default=False)),
                ("Hse_pc_np_d_comment", models.TextField(blank=True, null=True)),
                (
                    "Hse_pc_np_d_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("Hse_pc_np_d_approve", models.BooleanField(default=False)),
                ("Hse_pc_np_ddissaprove", models.BooleanField(default=False)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.contractor_registration",
                    ),
                ),
            ],
        ),
    ]
