# Generated by Django 4.1.2 on 2022-11-14 15:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contractor_name', models.CharField(blank=True, max_length=250)),
                ('con_address', models.CharField(blank=True, max_length=250)),
                ('licensed_no', models.IntegerField(blank=True, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=100, null=True)),
                ('coren_or_nemsa_competency', models.FileField(blank=True, null=True, upload_to='')),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='technicalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_survey_mapping', models.CharField(blank=True, max_length=100, null=True)),
                ('load_demand', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_sizing', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contract_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('connectiontype', models.CharField(choices=[('transformer installation', 'transformer installation'), ('transformer uprating', 'transformer uprating'), ('relocation', 'relocation'), ('change of transformer source', 'change of transformer source'), ('others', 'others')], default='transformer installation', max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=250)),
                ('voltage_ratio', models.CharField(blank=True, max_length=250)),
                ('route_length_km', models.CharField(blank=True, max_length=250)),
                ('add_house_no', models.CharField(blank=True, max_length=250)),
                ('add_street', models.CharField(blank=True, max_length=250)),
                ('add_town_or_city', models.CharField(blank=True, max_length=250)),
                ('add_lga', models.CharField(blank=True, max_length=250)),
                ('add_state', models.CharField(blank=True, max_length=250)),
                ('est_load_of_premises', models.CharField(blank=True, max_length=250)),
                ('useofpremises', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial'), ('industrial', 'industrial')], default='residential', max_length=100)),
                ('letter_of_donation_dss', models.FileField(blank=True, null=True, upload_to='')),
                ('nemsa_test_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('transformer_waranty', models.FileField(blank=True, null=True, upload_to='')),
                ('transformer_test_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('date_of_application', models.DateTimeField(auto_now_add=True, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercontractor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
