# Generated by Django 4.1.2 on 2022-12-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
