# Generated by Django 4.1.2 on 2022-12-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='cto_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='cto_is_contractor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='cto_is_contractor_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='hsch_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='hsch_is_contractor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='hsch_is_contractor_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='md_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='md_is_contractor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='md_is_contractor_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
