# Generated by Django 4.1.2 on 2022-11-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_contractor_registration_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="contract_application", name="Ctoapprove",),
        migrations.RemoveField(model_name="contract_application", name="Ctocomment",),
        migrations.RemoveField(model_name="contract_application", name="Ctodate",),
        migrations.RemoveField(
            model_name="contract_application", name="Ctodissaprove",
        ),
        migrations.RemoveField(
            model_name="contract_application", name="Hnp_D_approve",
        ),
        migrations.RemoveField(
            model_name="contract_application", name="Hnp_D_comment",
        ),
        migrations.RemoveField(model_name="contract_application", name="Hnp_D_date",),
        migrations.RemoveField(
            model_name="contract_application", name="Hnp_D_dissaprove",
        ),
        migrations.RemoveField(
            model_name="contract_application", name="Hse_pc_np_d_approve",
        ),
        migrations.RemoveField(
            model_name="contract_application", name="Hse_pc_np_d_comment",
        ),
        migrations.RemoveField(
            model_name="contract_application", name="Hse_pc_np_d_date",
        ),
        migrations.RemoveField(
            model_name="contract_application", name="Hse_pc_np_ddissaprove",
        ),
        migrations.RemoveField(model_name="contract_application", name="Md_approve",),
        migrations.RemoveField(model_name="contract_application", name="Md_date",),
        migrations.RemoveField(
            model_name="contract_application", name="Md_dissaprove",
        ),
        migrations.RemoveField(model_name="contract_application", name="Mdcomment",),
        migrations.RemoveField(model_name="contract_application", name="Te_approve",),
        migrations.RemoveField(
            model_name="contract_application", name="Te_dissaprove",
        ),
        migrations.RemoveField(model_name="contract_application", name="Tecomment",),
        migrations.RemoveField(model_name="contract_application", name="Tedate",),
        migrations.RemoveField(model_name="contract_application", name="Tm_approve",),
        migrations.RemoveField(model_name="contract_application", name="Tm_date",),
        migrations.RemoveField(
            model_name="contract_application", name="Tm_dissaprove",
        ),
        migrations.RemoveField(model_name="contract_application", name="Tmcomment",),
        migrations.RemoveField(model_name="contract_application", name="isCto",),
        migrations.RemoveField(model_name="contract_application", name="isHnp_D",),
        migrations.RemoveField(
            model_name="contract_application", name="isHse_pc_np_d",
        ),
        migrations.RemoveField(model_name="contract_application", name="isMd",),
        migrations.RemoveField(model_name="contract_application", name="isTe",),
        migrations.RemoveField(model_name="contract_application", name="isTm",),
    ]
