# Generated by Django 3.2 on 2024-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_contractoruser_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_application',
            name='eval_site_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract_application',
            name='precom_last_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
