# Generated by Django 4.1.2 on 2022-12-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_contractoruser_cto_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='in_approval_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
