# Generated by Django 3.2 on 2024-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20240122_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_application',
            name='eval_site_visit_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contract_application',
            name='precom_last_inspection_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
