# Generated by Django 4.1.2 on 2022-11-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_headquarter_region_businesshub_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesshub", old_name="rh", new_name="region",
        ),
        migrations.RenameField(
            model_name="contractoruser", old_name="bh", new_name="businesshub",
        ),
        migrations.RenameField(
            model_name="region", old_name="hq", new_name="headquarter",
        ),
    ]
