# Generated by Django 4.1.2 on 2022-11-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_remove_contract_application_ctoapprove_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractor_registration", name="user",),
    ]
