# Generated by Django 4.1.6 on 2023-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_contract_application_eval_2yrsloadproj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_application',
            old_name='public_transformer',
            new_name='public_connection',
        ),
    ]
