# Generated by Django 4.1.2 on 2022-11-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_remove_contractor_registration_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract_application",
            name="contractor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.contractor_registration",
            ),
        ),
    ]
