# Generated by Django 4.1.2 on 2022-12-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_contractoruser_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='declined_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
