# Generated by Django 4.1.6 on 2023-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_public_transformer_contract_application_public_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoruser',
            name='staff_type',
            field=models.CharField(choices=[('hqstaff', 'hqstaff'), ('regionstaff', 'regionstaff'), ('businesshubstaff', 'businesshubstaff'), ('servicecentrestaff', 'servicecentrestaff')], default='hqstaff', max_length=100),
        ),
    ]
