# Generated by Django 4.1.2 on 2022-11-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_rename_rh_businesshub_region_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesshub", old_name="bh_name", new_name="businesshub",
        ),
        migrations.RenameField(
            model_name="region", old_name="rh_name", new_name="region",
        ),
        migrations.RemoveField(model_name="region", name="headquarter",),
        migrations.DeleteModel(name="Headquarter",),
    ]
