# Generated by Django 3.2 on 2024-01-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_contractoruser_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractoruser',
            name='job_title',
        ),
    ]
