# Generated by Django 4.1.2 on 2022-11-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_bh_name_businesshub_businesshub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
