# Generated by Django 4.1.2 on 2022-11-07 21:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("portal", "0006_contractor_registration_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("contractor_name", models.CharField(blank=True, max_length=250)),
                ("con_address", models.CharField(blank=True, max_length=250)),
                ("licensed_no", models.IntegerField(blank=True, null=True)),
                ("tel_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "coren_or_nemsa_competency",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("reg_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="contract_application",
            name="contractor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercontractor",
                to="portal.contractoruser",
            ),
        ),
        migrations.DeleteModel(name="contractor_registration",),
    ]
