# Generated by Django 4.1.2 on 2022-11-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_contractoruser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesshub",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="businesshub",
            name="hubManager",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="businesshub",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="regionManager",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
