# Generated by Django 4.1.2 on 2022-11-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_businesshub_email_businesshub_hubmanager_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractoruser", name="businesshub",),
    ]
