# Generated by Django 4.1.2 on 2022-11-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_businesshub_email_businesshub_hubmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
