# Generated by Django 4.1.2 on 2022-12-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_contract_application_connection_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_application',
            name='security_receipt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
