# Generated by Django 3.2 on 2024-01-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_contractoruser_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoruser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
