# Generated by Django 4.1.2 on 2022-11-24 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_contractoruser_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractoruser',
            name='businesshub',
        ),
        migrations.RemoveField(
            model_name='region',
            name='email',
        ),
        migrations.RemoveField(
            model_name='region',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='businesshub',
            name='hubManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hub_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='regionManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contractor_Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hub_contractor', to='portal.businesshub')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor_hub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
