# Generated by Django 4.1.2 on 2022-11-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_contractoruser_businesshub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshub',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businesshub',
            name='phoneNumber',
        ),
    ]
