# Generated by Django 3.2 on 2024-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_contractoruser_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_application',
            name='eval_new4upgrade',
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_sglinediagram',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
