# Generated by Django 4.1.2 on 2022-12-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_contract_application_security_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='technicalEvaluation',
        ),
        migrations.AddField(
            model_name='contract_application',
            name='cto_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_applicant',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_dt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_estimated_load',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_site_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='eval_voltage_level',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='hm_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='npd_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='precom_last_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='precom_project_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='precom_project_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='te_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='tm_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='cto_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='hsch_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='md_memo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
