# Generated by Django 3.2 on 2024-05-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20240508_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_application',
            name='eval_bhub',
        ),
        migrations.RemoveField(
            model_name='contract_application',
            name='eval_region',
        ),
    ]
