# Generated by Django 4.1.2 on 2022-11-24 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_businesshub_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshub',
            name='technicalManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bh_technical_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='technicalManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_technical_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
