# Generated by Django 4.1.2 on 2022-11-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_businesshub_technicalmanager_region_technicalmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_application',
            name='profile_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='businesshub',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
