# Generated by Django 3.2 on 2024-05-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20240509_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractoruser',
            name='corenexpired',
        ),
        migrations.RemoveField(
            model_name='contractoruser',
            name='corenissued',
        ),
    ]
