# Generated by Django 4.1.2 on 2022-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_contract_application_eval_2yrsloadproj_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract_application",
            name="precom_cabletypsiz",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_cooling",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_current",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_distofnss",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_dwndrpcon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_earthresv",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_fdrname3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_fdrpillarcurr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_icomcablesiz",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_impedance",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_make",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_nemsavail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_nopoleht",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_nopolelt",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_nouprizercable",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_others",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_pcm",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_peakload",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_podepthlh",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_podeptht",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_qtyused",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_sizeconduct",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_sn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_ssfencedibedc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_supplysrc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_trsfcap",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_typfence",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_uprizercable",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_vectorgrp",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_voltratio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_wellallmetalprt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_wellgraveled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract_application",
            name="precom_yrsofman",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
