# Generated by Django 3.2 on 2024-05-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20240509_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='corenexpired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='corenissued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
