# Generated by Django 4.1.2 on 2023-01-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_alter_contract_application_eval_cumtilldate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractoruser", name="hsch_approved_by",),
        migrations.RemoveField(
            model_name="contractoruser", name="hsch_is_contractor_approved",
        ),
        migrations.RemoveField(
            model_name="contractoruser", name="hsch_is_contractor_approved_date",
        ),
        migrations.RemoveField(model_name="contractoruser", name="hsch_memo",),
    ]
