# Generated by Django 3.2 on 2024-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20240509_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoruser',
            name='corenexpired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractoruser',
            name='corenissued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
