# Generated by Django 3.2 on 2024-05-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20240509_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractoruser',
            name='corenexpired',
        ),
    ]
