# Generated by Django 3.2 on 2024-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20240515_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_application',
            name='ct_is_done',
            field=models.BooleanField(default=False),
        ),
    ]
