# Generated by Django 4.1.2 on 2023-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0017_contract_application_eval_otherdoc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract_application",
            name="capacity",
            field=models.CharField(
                choices=[
                    ("catd_50kva", "catd_50kva"),
                    ("catc_100kva", "catc_100kva"),
                    ("catb_1000kva", "catb_1000kva"),
                    ("cata_all", "cata_all"),
                ],
                default="catd_50kva",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contract_application",
            name="voltage_ratio",
            field=models.CharField(
                choices=[
                    ("elevenkv", "elevenkv"),
                    ("thirtythreekv", "thirtythreekv"),
                    ("fourhundred", "fourhundred"),
                ],
                default="elevenkv",
                max_length=100,
            ),
        ),
    ]
