# Generated by Django 3.2 on 2024-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_contract_application_ct_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_application',
            name='compdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
