# Generated by Django 4.1.2 on 2023-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0019_alter_contract_application_eval_voltage_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoruser",
            name="staff_type",
            field=models.CharField(
                choices=[("hqstaff", "hqstaff"), ("otherstaff", "otherstaff")],
                default="hqstaff",
                max_length=100,
            ),
        ),
    ]
