# Generated by Django 3.2 on 2024-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_contract_application_compdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_application',
            name='precom_cabletype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
