# Generated by Django 3.2 on 2024-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_contract_application_precom_cabletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_application',
            name='precom_voltratio',
            field=models.CharField(choices=[('elevenby400', 'elevenby400'), ('thirtythreeby400', 'thirtythreeby400'), ('thirtythreebyeleven', 'thirtythreebyeleven')], default='elevenby400', max_length=100),
        ),
    ]
