# Generated by Django 4.1.2 on 2023-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0021_contractoruser_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoruser",
            name="businesshub",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
