# Generated by Django 4.1.2 on 2023-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0022_contractoruser_businesshub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractoruser",
            name="staff_type",
            field=models.CharField(
                choices=[
                    ("hqstaff", "hqstaff"),
                    ("regionstaff", "regionstaff"),
                    ("businesshubstaff", "businesshubstaff"),
                ],
                default="hqstaff",
                max_length=100,
            ),
        ),
    ]
