# Generated by Django 4.1.2 on 2023-05-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_alter_contractoruser_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='approval_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
