# Generated by Django 4.1.2 on 2023-05-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_contractoruser_action_contractoruser_approval_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_application',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract_application',
            name='approval_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
