# Generated by Django 4.1.6 on 2023-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_contract_application_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_application',
            name='other_connection',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contract_application',
            name='route_length_km',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-20', '10-20'), ('over_20', 'over_20')], default='1-10', max_length=250),
        ),
        migrations.AlterField(
            model_name='contract_application',
            name='voltage_ratio',
            field=models.CharField(choices=[('elevenby400', 'elevenby400'), ('thirtythreeby400', 'thirtythreeby400'), ('thirtythreebyeleven', 'thirtythreebyeleven')], default='elevenby400', max_length=100),
        ),
    ]
