# Generated by Django 4.1.6 on 2023-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_contract_application_other_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='coren',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
