# Generated by Django 4.1.6 on 2023-09-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_contractoruser_coren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_application',
            name='transformer_test_cert',
        ),
    ]
