# Generated by Django 4.1.6 on 2023-12-03 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_contractoruser_staff_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contract_application',
            new_name='contract_applicationpub',
        ),
    ]
