# Generated by Django 3.2 on 2024-01-22 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
