# Generated by Django 3.2 on 2024-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0002_alter_contract_applicationpub_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='eval_datevisit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='precom_last_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
