# Generated by Django 3.2 on 2024-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0003_auto_20240122_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='date_of_visit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
