# Generated by Django 3.2 on 2024-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0004_alter_contract_applicationpub_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='eval_datevisit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='precom_last_inspection_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
