# Generated by Django 3.2 on 2024-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0005_auto_20240126_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='eval_bhub',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='eval_region',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='feeder_name',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='no_of_customers',
        ),
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='relieftype',
            field=models.CharField(choices=[('relief', 'relief'), ('operating', 'operating'), ('replacement', 'replacement'), ('new extension', 'new extension'), ('realignment', 'realignment'), ('relocation', 'relocation')], default='relief', max_length=100),
        ),
    ]
