# Generated by Django 3.2 on 2024-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0006_auto_20240508_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_applicationpub',
            old_name='nemsa_test_cert',
            new_name='nemsa_comp_cert',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='expected_billing',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='expected_gain',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='fdr_peakload',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='feeder_capacity',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='letter_of_donation_dss',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='load_tilldate',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='powertrans',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='source_fdr',
        ),
        migrations.RemoveField(
            model_name='contract_applicationpub',
            name='trans_rating',
        ),
        migrations.AlterField(
            model_name='contract_applicationpub',
            name='relieftype',
            field=models.CharField(choices=[('relief', 'relief'), ('up rating', 'up rating'), ('replacement', 'replacement'), ('new extension', 'new extension'), ('realignment', 'realignment'), ('relocation', 'relocation')], default='relief', max_length=100),
        ),
    ]
