# Generated by Django 3.2 on 2024-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0008_remove_contract_applicationpub_date_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_applicationpub',
            name='compdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='comprojcert',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='ct_is_completed',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='ct_is_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='ct_is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='inspbynemsa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='letterofdonation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='nemsatestcert',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract_applicationpub',
            name='projsignedoff',
            field=models.BooleanField(default=False),
        ),
    ]
