# Generated by Django 3.2 on 2024-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicportal', '0009_auto_20240518_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_applicationpub',
            name='precom_cabletype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
